import { Metadata } from "next";
import { ThemeProvider } from "next-themes"; // Import ThemeProvider
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="light">
        <body>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
